  version: '3.8'
  services:
    tasks_db:
      image: postgres:latest
      container_name: tasks-db
      ports:
        - "6543:5432"
      environment:
        - POSTGRES_DB=tasks
        - POSTGRES_USER=tasks
        - POSTGRES_PASSWORD=tasks


    task_service:
      build: .
      container_name: task_service
      ports:
        - "8083:8083"
      depends_on:
        - tasks_db
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://tasks_db:5432/tasks
        - SPRING_DATASOURCE_USERNAME=tasks
        - SPRING_DATASOURCE_PASSWORD=tasks