version: '3.8'
services:
  task_db:
    image: postgres:latest
    container_name: task-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=tasks
      - POSTGRES_PASSWORD=tasks


  task_web:
    build: task_service
    container_name: task_service
    ports:
      - "8083:8083"
    depends_on:
      - task_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://task_db:5432/tasks
      - SPRING_DATASOURCE_USERNAME=tasks
      - SPRING_DATASOURCE_PASSWORD=tasks